### ISSUE TITLE
Matrix multiplication 

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#13]
Input two matrices of any order and multiply them

**Comment by vansh15** [comment]
Please assign this issue to me

**Comment by Moumita-08** [comment]
I want to solve it, pls assign me.

**Comment by soumikbur** [comment]
> I want to solve it, pls assign me.

ok sure

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.

**Comment by Hasika-11** [comment]
hey can you please assign it to me

**Comment by iamrahul25** [comment]
Hey, can you assign this issue to me!

**Comment by ijaz-ali-dev** [comment]
Hey, I am interested to contribute to your repo by adding a requirement to it, can you please assign it to me?

**Comment by amritpalsingh52** [comment]
hello sir ,
 i wanted to learn things about github and conrtibution . if you please assign one issue come under the label of hacktoberfest i will highly wanted to solve
