### ISSUE TITLE
Occurence of pattern

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#16]
Write a program input a string and a pattern and count the occurrences of the pattern in the string.

**Comment by kashish0604** [comment]
hey @soumikbur can you assign this issue to me i can work on it

**Comment by kashish0604** [comment]
@soumikbur please accept my PR

**Comment by soumikbur** [comment]
> @soumikbur please accept my pr 
done @kashish0604

**Comment by ijaz-ali-dev** [comment]
Hey, I am interested to contribute to your repo by adding a requirement to it, can you please assign it to me?
