### ISSUE TITLE
String occurence

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#17]
Write a code  input a string and delete all consecutive odd occurrences of characters.

**Comment by kashish0604** [comment]
hey @soumikbur can you assign this issue to me i can work on it

**Comment by kashish0604** [comment]
@soumikbur please accept my PR

**Comment by soumikbur** [comment]
> hey @soumikbur can you assign this issue to me i can work on it

ok @kashish0604
