### ISSUE TITLE
Hello pattern 

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#19]
Write a code to print the following code
*    *        *****      *           *               **  
*    *        *            *           *             *      *
*****       *****      *           *             *       *
*    *        *            *           *             *      *
*    *       *****       *****    *****           **

**Comment by ijaz-ali-dev** [comment]
Hi dear, can u please add the October label to confirm and start my contribution

**Comment by soumikbur** [comment]
> Hi dear, can u please add the October label to confirm and start my contribution

is it ok??

**Comment by ijaz-ali-dev** [comment]
no dear its not ok you should learn first about it in details.

**Comment by Ishikasaraf20** [comment]
hey @soumikbur can you assign this issue to me i can work on it

**Comment by soumikbur** [comment]
> hey @soumikbur can you assign this issue to me i can work on it

ok

**Comment by NityaShukla0** [comment]
hey can you assign this to me pplease
