### ISSUE TITLE
Special characters 

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#23]
Write a code to enter a sentence and find number of vowels, consonants, spaces and special characters.

**Comment by sayan901** [comment]
Can you assign me?

**Comment by Ayush0826** [comment]
Hello sir! Can you assign this to me?....I can solve this

**Comment by soumikbur** [comment]
> Can you assign me?

ok done @sayan901

**Comment by avishagoyal08** [comment]
Can you please assign this to me? I can solve this in an effective way.
