### ISSUE TITLE
Even & Odd numbers array

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#25]
Write a code to input an array of n numbers and store the even numbers into an array even [] and odd numbers into an array odd []. Also display the count of even and odd numbers found.

**Comment by Moumita-08** [comment]
@soumikbur  can you assign this issue to me..

**Comment by soumikbur** [comment]
> @soumikbur can you assign this issue to me..

ok done @Moumita-08

**Comment by mehakbasrani** [comment]
i can do this. Please Assign.

**Comment by thviet84** [comment]
Can you assign this to me, pls? I feel interesting in this problem. I'll try to fix this
