### ISSUE TITLE
Portfolio Generator with Downloadable PDF

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#33]
HTML:

Create a form that allows users to input their portfolio details (name, skills, projects, experience).

Generate a live preview of the portfolio based on the user's inputs.

CSS:

Design the portfolio with a clean, professional layout.

Add responsive styles so that the portfolio looks good on both screens and printed versions.

JavaScript:

Implement functionality to dynamically generate a PDF version of the portfolio using libraries like html2pdf.js or jsPDF.

Allow users to customize the design (e.g., themes or color schemes) before downloading.

Optional: Use client-side storage (like localStorage) to save user inputs between sessions.

**Comment by Moumita-08** [comment]
Hey @soumikbur I'm interested in working on this issue. I can try. Can you assign me?

**Comment by soumikbur** [comment]
@Moumita-08 done 👍🏻✅
