### ISSUE TITLE
Web tech contribution 

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#37]
Add any type of frontend work as per your knowledge :)

**Comment by Moumita-08** [comment]
Hey @soumikbur I want to work on this issue. Can you assign me?

**Comment by nehaaaah123** [comment]
Hey @soumikbur ,can you please assign me this issue

**Comment by nehaaaah123** [comment]
Hey @soumikbur assign me this issue

**Comment by vipinyadav01** [comment]
Hey @soumikbur ,can you assign me this issue

**Comment by Blackie360** [comment]
assign me  ths issue

**Comment by Jprerna04** [comment]
Hi @soumikbur 
I've added the PR with the code for theme switching between light and dark mode using toggle button.
Pls check it!

**Comment by soumikbur** [comment]
> Hey @soumikbur ,can you assign me this issue

Yeah sure just get the job done dont wait for assignies 
If the code is correct then i will merge no worries ✌🏻

**Comment by Trishashetty11** [comment]
@soumikbur Please assign me the issue of Portfolio Generator .
