### ISSUE TITLE
Call by value & Call by reference 

### ISSUE THREAD

**Issue by soumikbur** [soumikbur/Hackoctoberfest2022#8]
Explain call by value and call by reference.

**Comment by AnirudhJalan** [comment]
can I do it

**Comment by soumikbur** [comment]
Sure @AnirudhJalan

**Comment by Ash0069** [comment]
Hi @soumikbur , please assign this to me

**Comment by Anonymous-Technopath** [comment]
Hi @soumikbur please assign this to me

**Comment by AnirudhJalan** [comment]
can i do it , please

**Comment by aditya10003** [comment]
Hii @soumikbur Can you assign this to me?

**Comment by ijaz-ali-dev** [comment]
Hey, I am interested to contribute to your repo by adding a requirement to it, can you please assign it to me?
